package com.example.qldathangsanpham.ui.product.spinner;

import java.util.HashMap;
import java.util.Map;

public enum Country {
    AC("AC", "Ascension Island", "🇦🇨"),
    AD("AD", "Andorra", "🇦🇩"),
    AE("AE", "United Arab Emirates", "🇦🇪"),
    AF("AF", "Afghanistan", "🇦🇫"),
    AG("AG", "Antigua & Barbuda", "🇦🇬"),
    AI("AI", "Anguilla", "🇦🇮"),
    AL("AL", "Albania", "🇦🇱"),
    AM("AM", "Armenia", "🇦🇲"),
    AO("AO", "Angola", "🇦🇴"),
    AQ("AQ", "Antarctica", "🇦🇶"),
    AR("AR", "Argentina", "🇦🇷"),
    AS("AS", "American Samoa", "🇦🇸"),
    AT("AT", "Austria", "🇦🇹"),
    AU("AU", "Australia", "🇦🇺"),
    AW("AW", "Aruba", "🇦🇼"),
    AX("AX", "Åland Islands", "🇦🇽"),
    AZ("AZ", "Azerbaijan", "🇦🇿"),
    BA("BA", "Bosnia & Herzegovina", "🇧🇦"),
    BB("BB", "Barbados", "🇧🇧"),
    BD("BD", "Bangladesh", "🇧🇩"),
    BE("BE", "Belgium", "🇧🇪"),
    BF("BF", "Burkina Faso", "🇧🇫"),
    BG("BG", "Bulgaria", "🇧🇬"),
    BH("BH", "Bahrain", "🇧🇭"),
    BI("BI", "Burundi", "🇧🇮"),
    BJ("BJ", "Benin", "🇧🇯"),
    BL("BL", "St. Barthélemy", "🇧🇱"),
    BM("BM", "Bermuda", "🇧🇲"),
    BN("BN", "Brunei", "🇧🇳"),
    BO("BO", "Bolivia", "🇧🇴"),
    BQ("BQ", "Caribbean Netherlands", "🇧🇶"),
    BR("BR", "Brazil", "🇧🇷"),
    BS("BS", "Bahamas", "🇧🇸"),
    BT("BT", "Bhutan", "🇧🇹"),
    BV("BV", "Bouvet Island", "🇧🇻"),
    BW("BW", "Botswana", "🇧🇼"),
    BY("BY", "Belarus", "🇧🇾"),
    BZ("BZ", "Belize", "🇧🇿"),
    CA("CA", "Canada", "🇨🇦"),
    CC("CC", "Cocos (Keeling) Islands", "🇨🇨"),
    CD("CD", "Congo - Kinshasa", "🇨🇩"),
    CF("CF", "Central African Republic", "🇨🇫"),
    CG("CG", "Congo - Brazzaville", "🇨🇬"),
    CH("CH", "Switzerland", "🇨🇭"),
    CI("CI", "Côte d’Ivoire", "🇨🇮"),
    CK("CK", "Cook Islands", "🇨🇰"),
    CL("CL", "Chile", "🇨🇱"),
    CM("CM", "Cameroon", "🇨🇲"),
    CN("CN", "China", "🇨🇳"),
    CO("CO", "Colombia", "🇨🇴"),
    CP("CP", "Clipperton Island", "🇨🇵"),
    CR("CR", "Costa Rica", "🇨🇷"),
    CU("CU", "Cuba", "🇨🇺"),
    CV("CV", "Cape Verde", "🇨🇻"),
    CW("CW", "Curaçao", "🇨🇼"),
    CX("CX", "Christmas Island", "🇨🇽"),
    CY("CY", "Cyprus", "🇨🇾"),
    CZ("CZ", "Czechia", "🇨🇿"),
    DE("DE", "Germany", "🇩🇪"),
    DG("DG", "Diego Garcia", "🇩🇬"),
    DJ("DJ", "Djibouti", "🇩🇯"),
    DK("DK", "Denmark", "🇩🇰"),
    DM("DM", "Dominica", "🇩🇲"),
    DO("DO", "Dominican Republic", "🇩🇴"),
    DZ("DZ", "Algeria", "🇩🇿"),
    EA("EA", "Ceuta & Melilla", "🇪🇦"),
    EC("EC", "Ecuador", "🇪🇨"),
    EE("EE", "Estonia", "🇪🇪"),
    EG("EG", "Egypt", "🇪🇬"),
    EH("EH", "Western Sahara", "🇪🇭"),
    ER("ER", "Eritrea", "🇪🇷"),
    ES("ES", "Spain", "🇪🇸"),
    ET("ET", "Ethiopia", "🇪🇹"),
    EU("EU", "European Union", "🇪🇺"),
    FI("FI", "Finland", "🇫🇮"),
    FJ("FJ", "Fiji", "🇫🇯"),
    FK("FK", "Falkland Islands", "🇫🇰"),
    FM("FM", "Micronesia", "🇫🇲"),
    FO("FO", "Faroe Islands", "🇫🇴"),
    FR("FR", "France", "🇫🇷"),
    GA("GA", "Gabon", "🇬🇦"),
    GB("GB", "United Kingdom", "🇬🇧"),
    GD("GD", "Grenada", "🇬🇩"),
    GE("GE", "Georgia", "🇬🇪"),
    GF("GF", "French Guiana", "🇬🇫"),
    GG("GG", "Guernsey", "🇬🇬"),
    GH("GH", "Ghana", "🇬🇭"),
    GI("GI", "Gibraltar", "🇬🇮"),
    GL("GL", "Greenland", "🇬🇱"),
    GM("GM", "Gambia", "🇬🇲"),
    GN("GN", "Guinea", "🇬🇳"),
    GP("GP", "Guadeloupe", "🇬🇵"),
    GQ("GQ", "Equatorial Guinea", "🇬🇶"),
    GR("GR", "Greece", "🇬🇷"),
    GS("GS", "South Georgia & South Sandwich Islands", "🇬🇸"),
    GT("GT", "Guatemala", "🇬🇹"),
    GU("GU", "Guam", "🇬🇺"),
    GW("GW", "Guinea-Bissau", "🇬🇼"),
    GY("GY", "Guyana", "🇬🇾"),
    HK("HK", "Hong Kong SAR China", "🇭🇰"),
    HM("HM", "Heard & McDonald Islands", "🇭🇲"),
    HN("HN", "Honduras", "🇭🇳"),
    HR("HR", "Croatia", "🇭🇷"),
    HT("HT", "Haiti", "🇭🇹"),
    HU("HU", "Hungary", "🇭🇺"),
    IC("IC", "Canary Islands", "🇮🇨"),
    ID("ID", "Indonesia", "🇮🇩"),
    IE("IE", "Ireland", "🇮🇪"),
    IL("IL", "Israel", "🇮🇱"),
    IM("IM", "Isle of Man", "🇮🇲"),
    IN("IN", "India", "🇮🇳"),
    IO("IO", "British Indian Ocean Territory", "🇮🇴"),
    IQ("IQ", "Iraq", "🇮🇶"),
    IR("IR", "Iran", "🇮🇷"),
    IS("IS", "Iceland", "🇮🇸"),
    IT("IT", "Italy", "🇮🇹"),
    JE("JE", "Jersey", "🇯🇪"),
    JM("JM", "Jamaica", "🇯🇲"),
    JO("JO", "Jordan", "🇯🇴"),
    JP("JP", "Japan", "🇯🇵"),
    KE("KE", "Kenya", "🇰🇪"),
    KG("KG", "Kyrgyzstan", "🇰🇬"),
    KH("KH", "Cambodia", "🇰🇭"),
    KI("KI", "Kiribati", "🇰🇮"),
    KM("KM", "Comoros", "🇰🇲"),
    KN("KN", "St. Kitts & Nevis", "🇰🇳"),
    KP("KP", "North Korea", "🇰🇵"),
    KR("KR", "South Korea", "🇰🇷"),
    KW("KW", "Kuwait", "🇰🇼"),
    KY("KY", "Cayman Islands", "🇰🇾"),
    KZ("KZ", "Kazakhstan", "🇰🇿"),
    LA("LA", "Laos", "🇱🇦"),
    LB("LB", "Lebanon", "🇱🇧"),
    LC("LC", "St. Lucia", "🇱🇨"),
    LI("LI", "Liechtenstein", "🇱🇮"),
    LK("LK", "Sri Lanka", "🇱🇰"),
    LR("LR", "Liberia", "🇱🇷"),
    LS("LS", "Lesotho", "🇱🇸"),
    LT("LT", "Lithuania", "🇱🇹"),
    LU("LU", "Luxembourg", "🇱🇺"),
    LV("LV", "Latvia", "🇱🇻"),
    LY("LY", "Libya", "🇱🇾"),
    MA("MA", "Morocco", "🇲🇦"),
    MC("MC", "Monaco", "🇲🇨"),
    MD("MD", "Moldova", "🇲🇩"),
    ME("ME", "Montenegro", "🇲🇪"),
    MF("MF", "St. Martin", "🇲🇫"),
    MG("MG", "Madagascar", "🇲🇬"),
    MH("MH", "Marshall Islands", "🇲🇭"),
    MK("MK", "Macedonia", "🇲🇰"),
    ML("ML", "Mali", "🇲🇱"),
    MM("MM", "Myanmar (Burma)", "🇲🇲"),
    MN("MN", "Mongolia", "🇲🇳"),
    MO("MO", "Macau SAR China", "🇲🇴"),
    MP("MP", "Northern Mariana Islands", "🇲🇵"),
    MQ("MQ", "Martinique", "🇲🇶"),
    MR("MR", "Mauritania", "🇲🇷"),
    MS("MS", "Montserrat", "🇲🇸"),
    MT("MT", "Malta", "🇲🇹"),
    MU("MU", "Mauritius", "🇲🇺"),
    MV("MV", "Maldives", "🇲🇻"),
    MW("MW", "Malawi", "🇲🇼"),
    MX("MX", "Mexico", "🇲🇽"),
    MY("MY", "Malaysia", "🇲🇾"),
    MZ("MZ", "Mozambique", "🇲🇿"),
    NA("NA", "Namibia", "🇳🇦"),
    NC("NC", "New Caledonia", "🇳🇨"),
    NE("NE", "Niger", "🇳🇪"),
    NF("NF", "Norfolk Island", "🇳🇫"),
    NG("NG", "Nigeria", "🇳🇬"),
    NI("NI", "Nicaragua", "🇳🇮"),
    NL("NL", "Netherlands", "🇳🇱"),
    NO("NO", "Norway", "🇳🇴"),
    NP("NP", "Nepal", "🇳🇵"),
    NR("NR", "Nauru", "🇳🇷"),
    NU("NU", "Niue", "🇳🇺"),
    NZ("NZ", "New Zealand", "🇳🇿"),
    OM("OM", "Oman", "🇴🇲"),
    PA("PA", "Panama", "🇵🇦"),
    PE("PE", "Peru", "🇵🇪"),
    PF("PF", "French Polynesia", "🇵🇫"),
    PG("PG", "Papua New Guinea", "🇵🇬"),
    PH("PH", "Philippines", "🇵🇭"),
    PK("PK", "Pakistan", "🇵🇰"),
    PL("PL", "Poland", "🇵🇱"),
    PM("PM", "St. Pierre & Miquelon", "🇵🇲"),
    PN("PN", "Pitcairn Islands", "🇵🇳"),
    PR("PR", "Puerto Rico", "🇵🇷"),
    PS("PS", "Palestinian Territories", "🇵🇸"),
    PT("PT", "Portugal", "🇵🇹"),
    PW("PW", "Palau", "🇵🇼"),
    PY("PY", "Paraguay", "🇵🇾"),
    QA("QA", "Qatar", "🇶🇦"),
    RE("RE", "Réunion", "🇷🇪"),
    RO("RO", "Romania", "🇷🇴"),
    RS("RS", "Serbia", "🇷🇸"),
    RU("RU", "Russia", "🇷🇺"),
    RW("RW", "Rwanda", "🇷🇼"),
    SA("SA", "Saudi Arabia", "🇸🇦"),
    SB("SB", "Solomon Islands", "🇸🇧"),
    SC("SC", "Seychelles", "🇸🇨"),
    SD("SD", "Sudan", "🇸🇩"),
    SE("SE", "Sweden", "🇸🇪"),
    SG("SG", "Singapore", "🇸🇬"),
    SH("SH", "St. Helena", "🇸🇭"),
    SI("SI", "Slovenia", "🇸🇮"),
    SJ("SJ", "Svalbard & Jan Mayen", "🇸🇯"),
    SK("SK", "Slovakia", "🇸🇰"),
    SL("SL", "Sierra Leone", "🇸🇱"),
    SM("SM", "San Marino", "🇸🇲"),
    SN("SN", "Senegal", "🇸🇳"),
    SO("SO", "Somalia", "🇸🇴"),
    SR("SR", "Suriname", "🇸🇷"),
    SS("SS", "South Sudan", "🇸🇸"),
    ST("ST", "São Tomé & Príncipe", "🇸🇹"),
    SV("SV", "El Salvador", "🇸🇻"),
    SX("SX", "Sint Maarten", "🇸🇽"),
    SY("SY", "Syria", "🇸🇾"),
    SZ("SZ", "Swaziland", "🇸🇿"),
    TA("TA", "Tristan da Cunha", "🇹🇦"),
    TC("TC", "Turks & Caicos Islands", "🇹🇨"),
    TD("TD", "Chad", "🇹🇩"),
    TF("TF", "French Southern Territories", "🇹🇫"),
    TG("TG", "Togo", "🇹🇬"),
    TH("TH", "Thailand", "🇹🇭"),
    TJ("TJ", "Tajikistan", "🇹🇯"),
    TK("TK", "Tokelau", "🇹🇰"),
    TL("TL", "Timor-Leste", "🇹🇱"),
    TM("TM", "Turkmenistan", "🇹🇲"),
    TN("TN", "Tunisia", "🇹🇳"),
    TO("TO", "Tonga", "🇹🇴"),
    TR("TR", "Turkey", "🇹🇷"),
    TT("TT", "Trinidad & Tobago", "🇹🇹"),
    TV("TV", "Tuvalu", "🇹🇻"),
    TW("TW", "Taiwan", "🇹🇼"),
    TZ("TZ", "Tanzania", "🇹🇿"),
    UA("UA", "Ukraine", "🇺🇦"),
    UG("UG", "Uganda", "🇺🇬"),
    UM("UM", "U.S. Outlying Islands", "🇺🇲"),
    UN("UN", "United Nations", "🇺🇳"),
    US("US", "United States", "🇺🇸"),
    UY("UY", "Uruguay", "🇺🇾"),
    UZ("UZ", "Uzbekistan", "🇺🇿"),
    VA("VA", "Vatican City", "🇻🇦"),
    VC("VC", "St. Vincent & Grenadines", "🇻🇨"),
    VE("VE", "Venezuela", "🇻🇪"),
    VG("VG", "British Virgin Islands", "🇻🇬"),
    VI("VI", "U.S. Virgin Islands", "🇻🇮"),
    VN("VN", "Vietnam", "🇻🇳"),
    VU("VU", "Vanuatu", "🇻🇺"),
    WF("WF", "Wallis & Futuna", "🇼🇫"),
    WS("WS", "Samoa", "🇼🇸"),
    XK("XK", "Kosovo", "🇽🇰"),
    YE("YE", "Yemen", "🇾🇪"),
    YT("YT", "Mayotte", "🇾🇹"),
    ZA("ZA", "South Africa", "🇿🇦"),
    ZM("ZM", "Zambia", "🇿🇲"),
    ZW("ZW", "Zimbabwe", "🇿🇼");

    private static Map<String, Country> map = new HashMap<>();

    private final String id;
    private final String name;
    private final String emoji;

    static {
        for (Country c : Country.values())
            map.put(c.id, c);
    }

    Country(String id, String name, String emoji) {
        this.id = id;
        this.name = name;
        this.emoji = emoji;
    }

    public String getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public String getEmoji() {
        return emoji;
    }

    public static Country getCountryById(String id) {
        return map.get(id);
    }
}